Added support for multiple executables.

diff --git a/atos-explore.in b/atos-explore.in
--- a/atos-explore.in
+++ b/atos-explore.in
@@ -50,7 +50,7 @@ Run Options
       -r <run_script> : run_script to be executed [default: $run_script]
 
 Executable File Options:
-      -e <executable> : executable to be instrumented [default: first arg of command]
+      -e <executables> : executables to be instrumented [default: args of command]
 
 Configuration Options:
       -C <path> : configuration path [default: $configuration_path]
@@ -74,7 +74,7 @@ tmpfile=`mktemp /tmp/atos-inst.XXXXXX`
 
 while getopts vhdqe:r:b:C: opt; do
     case $opt in
-	e) executable="$OPTARG"
+	e) executables="$OPTARG"
 	    ;;
 	C) configuration_path="$OPTARG"
 	    ;;
@@ -97,7 +97,7 @@ done
 
 shift $((OPTIND - 1))
 
-[ "$executable" != "" ] || executable="$1"
+[ "$executables" != "" ] || executables="$@"
 
 if [ "$configuration_path" = "" ]; then
     echo "`basename $0`: error: missing configuration path" >&2
@@ -111,15 +111,19 @@ fi
 configuration_path=`cd "$configuration_path"; pwd`
 
 if [ -f "$configuration_path/targets" ]; then
-    executable=`head -1 "$configuration_path/targets"`
+    executables=`cat "$configuration_path/targets"`
 fi
-if [ "$executable" = "" ]; then
-    echo "`basename $0`: error: missing executable" >&2
+if [ "$executables" = "" ]; then
+    echo "error: `basename $0`: missing executable target" >&2
     exit 1
 fi
 
-identifier=`basename "$executable"`
-
+identifier=""
+sep=""
+for i in $executables; do
+    identifier="$identifier$sep"`basename "$i"`
+    sep="-"
+done
 
 if [ "$build_script" != "" ]; then
     [ "$quiet" = "1" ] || echo "Auditing build ($identifier)..."
@@ -132,7 +136,7 @@ if [ "$run_script" != "" ]; then
 fi
 
 [ "$quiet" = "1" ] || echo "Computing build dependencies ($identifier)..."
-$dir/atos-deps "$executable"
+$dir/atos-deps $executables
 
 [ "$quiet" = "1" ] || echo "Cleaning all profiles..."
 rm -rf "$configuration_path"/profiles
diff --git a/atos-play.in b/atos-play.in
--- a/atos-play.in
+++ b/atos-play.in
@@ -29,10 +29,12 @@ PROOT=${PROOT:-proot}
 
 configuration_path="./atos-configurations"
 objective=time
-executable=""
+executables=""
+identifier=""
 quiet="0"
 dryrun=""
 print=""
+ref=0
 
 version() {
     echo "atos-play version @VERSION@"
@@ -45,10 +47,12 @@ Usage: atos-play [options] [--] [command...]
 
 Objective Options:
       -f <objective> : defined the objective function [default: $objective]
+      -r : get reference results
 
 Configuration Options:
       -C <path> : configuration path [default: $configuration_path]
-      -e <executable>: executable target [default: inferred from configuration]
+      -e <executables>: executables targets [default: inferred from configuration]
+      -i <identifier> : identifier of run [default: executables basename]
 
 Build Configuration:
       -n : dry run, output build commands only
@@ -68,17 +72,21 @@ cleanup() {
 trap "cleanup; exit 3" TERM STOP
 trap "cleanup" EXIT
 
-while getopts vhqnpC:f:e: opt; do
+while getopts vhqnprC:f:e:i: opt; do
     case $opt in
 	f) objective="$OPTARG"
 	    ;;
 	C) configuration_path="$OPTARG"
 	    ;;
-	e) executable="$OPTARG"
+	e) executables="$OPTARG"
+	    ;;
+	i) identifier="$OPTARG"
 	    ;;
 	n) dryrun=1
 	    ;;
 	p) print=1
+	    ;;
+	r) ref=1
 	    ;;
 	q) quiet=1
 	    ;;
@@ -99,21 +107,27 @@ if [ ! -f "$results_db" ]; then
     exit 1
 fi
 
-if [ "$executable" = "" ]; then
-    executable=`head -1 $configuration_path/targets`
-fi
-
-if [ "$executable" = "" ]; then
-    echo "error: `basename $0`: not target specified" >&2
-    exit 1
+if [ "$identifier" = "" ]; then
+    if [ "$executables" = "" ]; then
+	if [ -f "$configuration_path/targets" ]; then
+	    executables=`cat "$configuration_path/targets"`
+	else
+	    echo "error: `basename $0`: error: no target executable and no identifier specified" >&2
+	    exit 1
+	fi
+    fi
+    identifier=""
+    sep=""
+    for i in $executables; do
+	identifier="$identifier$sep"`basename "$i"`
+	sep="-"
+    done
 fi
 
 if [ "$objective" != time -a "$objective" != size ]; then
     echo "error: `basename $0`: unknown objective: $objective" >&2
     exit 1
 fi
-
-identifier=`basename "$executable"`
 
 best() {
     grep "^ATOS: $identifier:" $results_db  | grep " $objective:" | sort -n -k 5 | head -1 | awk '{print $3}' | sed 's/:$//'
@@ -123,14 +137,19 @@ get_options() {
     grep "^ATOS: $identifier: $configuration: conf:" $results_db | sed "s/ATOS: $identifier: $configuration: conf: //"
 }
 
-configuration=`best`
+if [ "$ref" = 1 ]; then
+    configuration=REF
+    options=""
+else
+    configuration=`best`
+    options=`get_options`
+fi
 
 if [ "$print" = 1 ]; then
     grep "^ATOS: $identifier: $configuration:" $results_db
     exit 0
 fi
 
-options=`get_options`
 [ "$quiet" = "1" ] || echo "Playing optimized build $identifier:$configuration..."
 exec $dir/atos-opt ${dryrun:+-n} -a "$options"
 
diff --git a/atos-run.in b/atos-run.in
--- a/atos-run.in
+++ b/atos-run.in
@@ -27,7 +27,7 @@ dir=`dirname $0`
 dir=`cd $dir; pwd`
 PROOT=${PROOT:-proot}
 
-executable=""
+executables=""
 identifier=""
 variant=""
 fd=""
@@ -48,10 +48,10 @@ usage() {
 Usage: atos-run [options] [--] [command...]
 
 Executable File Options:
-      -e <executable> : executable to be instrumented [default: first arg of command]
+      -e <executables> : executables to be instrumented [default: first arg of command]
 
 Identification options:
-      -i <identifier> : identifier of run [default: executable basename]
+      -i <identifier> : identifier of run [default: executables basename]
       -w <variant> : identifier of variant [default: REF]
       -a <options> : if specified, infer variant from option set
 
@@ -88,7 +88,7 @@ tmpfile2=`mktemp /tmp/atos-inst.XXXXXX`
 
 while getopts vhro:f:e:a:i:w:u:g:C: opt; do
     case $opt in
-	e) executable="$OPTARG"
+	e) executables="$OPTARG"
 	    ;;
 	i) identifier="$OPTARG"
 	    ;;
@@ -119,17 +119,22 @@ done
 
 shift $((OPTIND - 1))
 
-if [ "$executable" = "" ]; then
+if [ "$executables" = "" ]; then
     if [ -f "$configuration_path/targets" ]; then
-	executable=`head -1 $configuration_path/targets`
+	executables=`cat "$configuration_path/targets"`
     else
-	echo "`basename $0`: error: missing command arguments" >&2
+	echo "error: `basename $0`: error: no target executable specified" >&2
 	exit 1
     fi
 fi
 
 if [ "$identifier" = "" ]; then
-    identifier=`basename "$executable"`
+    identifier=""
+    sep=""
+    for i in $executables; do
+	identifier="$identifier$sep"`basename "$i"`
+	sep="-"
+    done
 fi
 
 if [ "$g_set" = 1 -a "$u_set" = 1 ]; then
@@ -178,21 +183,28 @@ fi
 
 
 get_size() {
-    local exe="${1?}"
-    exe="`which "$exe"`"
+    local exes="${1?}"
+    local -i size=0
+    for exe in $exes; do
+	exe="`which "$exe"`"
+	local -i exe_size=`/usr/bin/size "$exe" | tail -1 | awk '{print $4;}'`
+	size=$((size+exe_size))
+    done
     if [ "$file" != "" ]; then
-	/usr/bin/size "$exe" | tail -1 | awk '{print "ATOS: '"$identifier"': '"$variant"': size: ", $4;}' >>"$file"
+	echo "ATOS: $identifier: $variant: size: $size" >>"$file"
     else
-	/usr/bin/size "$exe" | tail -1 | awk '{print "ATOS: '"$identifier"': '"$variant"': size: ", $4;}' >&$fd
+	echo "ATOS: $identifier: $variant: size: $size" >&$fd
     fi
 }
 
 get_time() {
+    local -i time
     /usr/bin/time -p ${1+"$@"} 2>&1 | tee $tmpfile | sed -e '/^real /d' -e '/^user /d' -e '/^sys /d'
+    time=`tail -3 $tmpfile | awk '{if ($1 == "user") { print int($2 * 1000); }}'`
     if [ "$file" != "" ]; then
-	tail -3 $tmpfile | awk '{if ($1 == "user") { print "ATOS: '"$identifier"': '"$variant"': time: ", int($2 * 1000); }}' >>"$file"
+	echo "ATOS: $identifier: $variant: time: $time" >>"$file"
     else
-	tail -3 $tmpfile | awk '{if ($1 == "user") { print "ATOS: '"$identifier"': '"$variant"': time: ", int($2 * 1000); }}' >&$fd
+	echo "ATOS: $identifier: $variant: time: $time" >&$fd
     fi
 }
 
@@ -209,4 +221,4 @@ if [ -f "$configuration_path/run.sh" ]; then
 else
     get_time ${1+"$@"}
 fi
-get_size "$executable"
+get_size "$executables"
