Added support for quiet option. Store build and run logs.

diff --git a/atos-explore.in b/atos-explore.in
--- a/atos-explore.in
+++ b/atos-explore.in
@@ -34,6 +34,7 @@ configuration_path="./atos-configurations"
 verbose="0"
 quiet="0"
 clean="0"
+opt_q=""
 
 version() {
     echo "atos-explore version @VERSION@"
@@ -88,7 +89,7 @@ while getopts vhdqce:r:b:C: opt; do
 	    ;;
 	d) verbose=1
 	    ;;
-	q) quiet=1
+	q) quiet=1; opt_q=-q
 	    ;;
 	v) version; exit 0
 	    ;;
@@ -110,8 +111,13 @@ fi
 
 mkdir -p "$configuration_path"
 configuration_path=`cd "$configuration_path"; pwd`
+if [ "$clean" = "1" ]; then
+    [ "$quiet" = "1" ] || echo "Cleaning all profiles..."
+    rm -rf "$configuration_path"/profiles
+    [ "$quiet" = "1" ] || echo "Cleaning all results..."
+    rm -rf "$configuration_path"/results.db
+fi
 
-identifier="session-$$"
 if [ -f "$configuration_path/targets" ]; then
     executables=`cat "$configuration_path/targets"`
 fi
@@ -122,59 +128,40 @@ if [ "$executables" = "" ]; then
 fi
 
 if [ "$build_script" != "" ]; then
-    [ "$quiet" = "1" ] || echo "Auditing build ($identifier)..."
-    $dir/atos-audit $build_script
+    $dir/atos-audit $opt_q $build_script
 fi
 
 if [ "$run_script" != "" ]; then
-    [ "$quiet" = "1" ] || echo "Auditing run ($identifier)..."
-    $dir/atos-raudit $run_script
+    $dir/atos-raudit $opt_q $run_script
 fi
 
-[ "$quiet" = "1" ] || echo "Computing build dependencies ($identifier)..."
-$dir/atos-deps $executables
+$dir/atos-deps $opt_q $executables
 
-if [ "$clean" = "1" ]; then
-    [ "$quiet" = "1" ] || echo "Cleaning all profiles ($identifier)..."
-    rm -rf "$configuration_path"/profiles
-    [ "$quiet" = "1" ] || echo "Cleaning all results ($identifier)..."
-    rm -rf "$configuration_path"/results.db
-fi
-
-[ "$quiet" = "1" ] || echo "Running reference execution ($identifier: REF)..."
-$dir/atos-run -r || echo "Variant run FAILURE ($identifier: REF)" 
+$dir/atos-run $opt_q -r # Will stop there if reference run fails
 
 for gopt in "-O1" "-O2" "-Os" "-O3"; do
     for opts in "" "-flto"; do
 	options="$gopt $opts"
-	variant=`echo $options | sed 's/ //g'`
-	[ "$quiet" = "1" ] || echo "Building ($identifier: $options)..."
-	$dir/atos-opt -a "$options" >"$configuration_path/build$variant.log" 2>&1 || echo "Variant build FAILURE ($identifier: $options)" 
-	[ "$quiet" = "1" ] || echo "Running ($identifier: $options)..."
-	$dir/atos-run -r -a "$options" >"$configuration_path/run$variant.log" 2>&1 || echo "Variant run FAILURE ($identifier: $options)" 
+	$dir/atos-opt $opt_q -a "$options" && $dir/atos-run $opt_q -r -a "$options" || true
     done
-    [ "$quiet" = "1" ] || echo "Profiling build ($identifier: -fprofile-generate $gopt)..."
-    pvariant=`echo $gopts | sed 's/ //g'`
-    $dir/atos-profile -g "$gopt" >"$configuration_path/build-fprofile-generate$pvariant.log" 2>&1 || failure=true
+    failure=false
+    $dir/atos-profile $opt_q -g "$gopt" || failure=true
     if $failure; then
-	echo "Variant profiling FAILURE ($identifier: -fprofile-generate $gopt)" 
+	# skipping profile variants
+	:
     else
 	for opts in "" "-flto" "-funroll-loops" "-flto -funroll-loops"; do
 	    options="$gopt $opts"
-	    variant=`echo $options | sed 's/ //g'`
-	    [ "$quiet" = "1" ] || echo "Building ($identifier: -fprofile-use $options)..."
-	    $dir/atos-opt -u "$gopt" -a "$options" >"$configuration_path/build-fprofile-use$pvariant$variant.log" 2>&1 || echo "Variant build FAILURE ($identifier: -fprofile-use $options)" 
-	    [ "$quiet" = "1" ] || echo "Running ($identifier: -fprofile-use $options)..."
-	    $dir/atos-run -r -u "$gopt" -a "$options" >"$configuration_path/run-fprofile-use$pvariant$variant.log" 2>&1 || echo "Variant run FAILURE ($identifier: -fprofile-use $options)" 
+	    $dir/atos-opt $opt_q -u "$gopt" -a "$options" && $dir/atos-run $opt_q -r -u "$gopt" -a "$options" || true
 	done
     fi
 done
 if [ "$quiet" != "1" ]; then
-    echo "Best performance variant ($identifier)..."
+    echo "Best performance variant..."
     $dir/atos-play -p -f time
-    echo "Best size variant ($identifier)..."
+    echo "Best size variant..."
     $dir/atos-play -p -f size
 fi
 if [ "$quiet" != "1" ]; then
-    echo "Completed ($identifier)."
+    echo "Completed."
 fi
diff --git a/atos-opt.in b/atos-opt.in
--- a/atos-opt.in
+++ b/atos-opt.in
@@ -36,6 +36,8 @@ u_set=0
 uopts=""
 g_set=0
 gopts=""
+quiet=0
+variant=""
 
 version() {
     echo "atos-opt version @VERSION@"
@@ -52,6 +54,7 @@ Driver Options:
 
 Optimization Options:
       -a "options" : append given options to the compilation commands [default: $options]
+      -w <variant> : identifier of variant [default: REF or infered from -a]
 
 Configuration Options:
       -C <path> : configuration path [default: $configuration_path]
@@ -66,6 +69,7 @@ Profile options:
       -p <path> : path to profile files [default: $configuration_path/profiles/<pvariant>]
 
 Misc Options
+      -q : quiet output
       -h : output usage
       -v : output version
 
@@ -78,7 +82,7 @@ cleanup() {
 trap "cleanup; exit 3" TERM STOP
 trap "cleanup" EXIT
 
-while getopts vhnC:j:c:r:a:u:g:p: opt; do
+while getopts vhqnw:C:j:c:r:a:u:g:p: opt; do
     case $opt in
 	a) options="$OPTARG"
 	    ;;
@@ -94,7 +98,11 @@ while getopts vhnC:j:c:r:a:u:g:p: opt; do
 	    ;;
 	g) g_set=1; gopts="$OPTARG"
 	    ;;
+	w) variant="$OPTARG"
+	    ;;
 	n) dryrun=1
+	    ;;
+	q) quiet=1
 	    ;;
 	C) configuration_path="$OPTARG"
 	    ;;
@@ -128,7 +136,7 @@ if [ "$g_set" = 1 ]; then
 	profile_path="$configuration_path/profiles/`variant_hash $pvariant`"
     fi
     mkdir -p "$profile_path"
-    echo $pvariant > $profile_path/variant.txt
+    echo "$pvariant" > "$profile_path/variant.txt"
     profile_path=`cd "$profile_path"; pwd`
     find "$profile_path" -name '*.gcda' | xargs rm -f
     APFLAGS="-fprofile-generate -fprofile-dir=$profile_path"
@@ -147,9 +155,30 @@ if [ "$u_set" = 1 ]; then
     APFLAGS="-fprofile-use -fprofile-correction -Wno-error=coverage-mismatch -fprofile-dir=$profile_path"
 fi
 
-# If the configuration path contains a build.mk execute it
+if [ "$variant" = "" ]; then
+    if [ "$options" != "" -o "$pvariant" != "" ]; then
+	if [ "$g_set" = 1 ]; then
+	    variant=OPT-fprofile-generate$pvariant`echo $options | sed 's/ //g'`
+	elif [ "$u_set" = 1 ]; then
+	    variant=OPT-fprofile-use$pvariant`echo $options | sed 's/ //g'`
+	else
+	    variant=OPT$pvariant`echo $options | sed 's/ //g'`
+	fi
+    else
+	variant=REF
+    fi
+fi
+
+failure=false
+mkdir -p "$configuration_path/logs"
+[ "$quiet" = "1" ] || echo "Building variant $variant..."
 if [ -f "$configuration_path/build.mk" ]; then
-    exec make ${dryrun:+-n} -j $jobs -f $configuration_path/build.mk ACFLAGS="$APFLAGS $options"
+    # If the configuration path contains a build.mk execute it
+    make ${dryrun:+-n} -j $jobs -f $configuration_path/build.mk ACFLAGS="$APFLAGS $options" >"$configuration_path/logs/build-$variant.log" 2>&1 || failure=true
 else
-    exec env PROOT_ADDON_CC_OPTS=1 PROOT_ADDON_CC_OPTS_ARGS="$APFLAGS $options" PROOT_ADDON_CC_OPTS_CCRE="$ccregexp" $PROOT -w $PWD / ${1+"$@"}
+    env PROOT_ADDON_CC_OPTS=1 PROOT_ADDON_CC_OPTS_ARGS="$APFLAGS $options" PROOT_ADDON_CC_OPTS_CCRE="$ccregexp" $PROOT -w $PWD / ${1+"$@"}  >"$configuration_path/logs/build-$variant.log"  2>&1 || failure=true
+fi
+if $failure; then
+    [ "$quiet" = 1 ] || echo "FAILURE while building variant $variant..."
+    exit 2
 fi
diff --git a/atos-run.in b/atos-run.in
--- a/atos-run.in
+++ b/atos-run.in
@@ -37,6 +37,8 @@ u_set=0
 uopts=""
 g_set=0
 gopts=""
+quiet=0
+silent=0
 
 version() {
     echo "atos-run version @VERSION@"
@@ -64,12 +66,14 @@ Configuration Options:
 
 Recordiong options:
       -r : record results
+      -s : silent mode, do not emit pers/size results
 
 Profile options:
       -u "$opts" : use profile variant deduced by $opts [default: none]
       -g "$opts" : use profile variant deduced by $opts [default: none]
 
 Misc Options
+      -q : quiet output
       -h : output usage
       -v : output version
 
@@ -86,7 +90,7 @@ tmpfile=`mktemp /tmp/atos-inst.XXXXXX`
 tmpfile2=`mktemp /tmp/atos-inst.XXXXXX`
 
 
-while getopts vhro:f:e:a:i:w:u:g:C: opt; do
+while getopts vhqrso:f:e:a:i:w:u:g:C: opt; do
     case $opt in
 	e) executables="$OPTARG"
 	    ;;
@@ -107,6 +111,10 @@ while getopts vhro:f:e:a:i:w:u:g:C: opt; do
 	C) configuration_path="$OPTARG"
 	    ;;
 	r) record=1
+	    ;;
+	s) silent=1
+	    ;;
+	q) quiet=1
 	    ;;
 	v) version; exit 0
 	    ;;
@@ -181,6 +189,7 @@ if [ "$file" != "" -a "$fd" != "" ]; then
     exit 1
 fi
 
+[ "$quiet" = 1 ] || echo "Running variant $variant..."
 exe_time=0
 exe_size=0
 failure=false
@@ -202,30 +211,35 @@ get_time() {
     exe_time=`tail -3 $tmpfile | awk '{if ($1 == "user") { print int($2 * 1000); }}'`
 }
 
+mkdir -p "$configuration_path/logs"
+
 if [ -f "$configuration_path/run.sh" ]; then
-    get_time "$configuration_path/run.sh"
+    get_time "$configuration_path/run.sh" > "$configuration_path/logs/run-$variant.log" 2>&1
 else
-    get_time ${1+"$@"}
+    get_time ${1+"$@"} > "$configuration_path/logs/run-$variant.log" 2>&1
 fi
-get_size "$executables"
+get_size "$executables" >> "$configuration_path/logs/run-$variant.log" 2>&1
 
 if $failure; then
     exe_size=FAILURE
     exe_time=FAILURE
 fi
 
-if [ "$file" != "" ]; then
-    echo "ATOS: $identifier: $variant: version: `$0 -v | awk '{print $3;}'`" >>"$file"
-    echo "ATOS: $identifier: $variant: conf: $options" >>"$file"
-    echo "ATOS: $identifier: $variant: size: $exe_size" >>"$file"
-    echo "ATOS: $identifier: $variant: time: $exe_time" >>"$file"
-else
-    echo "ATOS: $identifier: $variant: version: `$0 -v`" >&$fd
-    echo "ATOS: $identifier: $variant: conf: $options" >&$fd
-    echo "ATOS: $identifier: $variant: size: $exe_size" >&$fd
-    echo "ATOS: $identifier: $variant: time: $exe_time" >&$fd
+if [ "$silent" != 1 ]; then
+    if [ "$file" != "" ]; then
+	echo "ATOS: $identifier: $variant: version: `$0 -v | awk '{print $3;}'`" >>"$file"
+	echo "ATOS: $identifier: $variant: conf: $options" >>"$file"
+	echo "ATOS: $identifier: $variant: size: $exe_size" >>"$file"
+	echo "ATOS: $identifier: $variant: time: $exe_time" >>"$file"
+    else
+	echo "ATOS: $identifier: $variant: version: `$0 -v`" >&$fd
+	echo "ATOS: $identifier: $variant: conf: $options" >&$fd
+	echo "ATOS: $identifier: $variant: size: $exe_size" >&$fd
+	echo "ATOS: $identifier: $variant: time: $exe_time" >&$fd
+    fi
 fi
 
 if $failure; then
+    [ "$quiet" = 1 ] || echo "FAILURE while running variant $variant..."
     exit 2
 fi
