atos-config: added acf plugin info to compiler description.

diff --git a/atos-explore-acf.in b/atos-explore-acf.in
--- a/atos-explore-acf.in
+++ b/atos-explore-acf.in
@@ -144,56 +144,15 @@ config_query() {
     $libdir/atos_lib.py config -C $configuration_path -u -t -q $*
 }
 
-if [ "`config_query '$.compilers[*].name'`" != "gcc" ]; then
-    echo "`basename $0`: error: acf only usable with gcc compiler" >&2
-    exit 1
-fi
-
-gcc_version=`config_query '$.compilers[*].version'`
-
-gcc_machine=`config_query '$.compilers[*].target'`
-
-case "${gcc_machine}" in
-    x86_64-*)
-      machine_dir=x86_64
-      ;;
-    i386-* | i686-*)
-      machine_dir=i386
-      ;;
-    arm-*)
-      machine_dir=arm
-      ;;
-    sh-*)
-      machine_dir=sh4
-      ;;
-    *)
-      echo "error: host machine ${gcc_machine} not supported by acf plugin"
-      exit 1
-      ;;
-esac
-
-# for gcc version, only take into account Major/Minor numbers
-if [ ! -f ${libdir}/plugins/gcc-${gcc_version}/${machine_dir}/${acf_plugin} ]; then
-    # get short version limited to Major/Minor
-    vers=`echo $gcc_version | sed 's/\([0-9]*\.[0-9]*\).*/\1/'`
-    gcc_list=`\ls -d ${libdir}/plugins/gcc-${vers}* 2>/dev/null| sort -r`
-    # Take more recent gcc version matching Major/Minor
-    for gcc_el in ${gcc_list}; do
-	if [ -f ${gcc_el}/${machine_dir}/${acf_plugin} ]; then
-	    acf_plugin_path=${gcc_el}/${machine_dir}/${acf_plugin}
-	    break;
-	fi
-    done
-else
-    acf_plugin_path=${libdir}/plugins/gcc-${gcc_version}/${machine_dir}/${acf_plugin}
-fi
+acf_plugin_path=`config_query '$.compilers[*].plugin_acf'`
 
 if [ "${acf_plugin_path}" == "" ]; then
-    echo "error: gcc version not supported by acf plugin: gcc-${vers}.*"
+    echo "`basename $0`: error: compiler not supported by acf plugin" >&2
     exit 1
 fi
-if [ ! -f ${acf_plugin_path} ]; then
-    echo "error: acf plugin not found: $acf_plugin_path" >&2
+
+if [ "`config_query '$.compilers[*].plugins_enabled'`" != "1" ]; then
+    echo "`basename $0`: error: compiler does not support plugins" >&2
     exit 1
 fi
 
