atos-explore: fixed -C option handling.

diff --git a/atos-explore.in b/atos-explore.in
--- a/atos-explore.in
+++ b/atos-explore.in
@@ -149,51 +149,51 @@ if [ "$clean" = "1" ]; then
 fi
 
 if [ "$build_script" != "" ]; then
-    $dir/atos-audit $opt_q $opt_rebuild $build_script
+    $dir/atos-audit -C "$configuration_path" $opt_q $opt_rebuild $build_script
 elif [ ! -f "$configuration_path/build.audit" ]; then
     echo "`basename $0`: error: missing build audit, use -b option for specifying build script or use atos-audit tool" >&2
     exit 1
 fi
 
 if [ "$run_script" != "" ]; then
-    $dir/atos-raudit $opt_q -t "$get_results_script" $run_script
+    $dir/atos-raudit -C "$configuration_path" $opt_q -t "$get_results_script" $run_script
 elif [ ! -f "$configuration_path/run.audit" ]; then
     echo "`basename $0`: error: missing run audit, use -r option for specifying run script or use atos-raudit tool" >&2
     exit 1
 fi
 
 if [ "$opt_rebuild" = "" ]; then
-    $dir/atos-deps $opt_q $executables
+    $dir/atos-deps -C "$configuration_path" $opt_q $executables
 else
     if [ "$get_results_script" = "" ]; then
 	echo "$executables" >"$configuration_path"/targets
     fi
 fi
 	
-$dir/atos-run $opt_q -r # Will stop there if reference run fails
+$dir/atos-run -C "$configuration_path" $opt_q -r # Will stop there if reference run fails
 
 for gopt in "-O1" "-O2" "-Os" "-O3"; do
     for opts in "" "-flto"; do
 	options="$gopt $opts"
-	$dir/atos-opt $opt_q -a "$options" && $dir/atos-run $opt_q -r -a "$options" || true
+	$dir/atos-opt -C "$configuration_path" $opt_q -a "$options" && $dir/atos-run -C "$configuration_path" $opt_q -r -a "$options" || true
     done
     failure=false
-    $dir/atos-profile $opt_q -b "$remote_profile_path" -g "$gopt" || failure=true
+    $dir/atos-profile -C "$configuration_path" $opt_q -b "$remote_profile_path" -g "$gopt" || failure=true
     if $failure; then
 	# skipping profile variants
 	:
     else
 	for opts in "" "-flto" "-funroll-loops" "-flto -funroll-loops"; do
 	    options="$gopt $opts"
-	    $dir/atos-opt $opt_q -u "$gopt" -a "$options" && $dir/atos-run $opt_q -b "$remote_profile_path" -r -u "$gopt" -a "$options" || true
+	    $dir/atos-opt -C "$configuration_path" $opt_q -u "$gopt" -a "$options" && $dir/atos-run -C "$configuration_path" $opt_q -b "$remote_profile_path" -r -u "$gopt" -a "$options" || true
 	done
     fi
 done
 if [ "$quiet" != "1" ]; then
     echo "Best performance variant..."
-    $dir/atos-play -p -f time
+    $dir/atos-play -C "$configuration_path" -p -f time
     echo "Best size variant..."
-    $dir/atos-play -p -f size
+    $dir/atos-play -C "$configuration_path" -p -f size
 fi
 if [ "$quiet" != "1" ]; then
     echo "Completed."
