atos-explore: add errors when no audi/raudit have been setup.

diff --git a/atos-explore.in b/atos-explore.in
--- a/atos-explore.in
+++ b/atos-explore.in
@@ -129,10 +129,16 @@ fi
 
 if [ "$build_script" != "" ]; then
     $dir/atos-audit $opt_q $build_script
+elif [ ! -f "$configuration_path/build.audit" ]; then
+    echo "`basename $0`: error: missing build audit, use -b option for specifying build script or use atos-audit tool" >&2
+    exit 1
 fi
 
 if [ "$run_script" != "" ]; then
     $dir/atos-raudit $opt_q $run_script
+elif [ ! -f "$configuration_path/run.audit" ]; then
+    echo "`basename $0`: error: missing run audit, use -r option for specifying run script or use atos-raudit tool" >&2
+    exit 1
 fi
 
 $dir/atos-deps $opt_q $executables
