atos-run/explore: added -n option

diff --git a/atos-explore.in b/atos-explore.in
--- a/atos-explore.in
+++ b/atos-explore.in
@@ -34,6 +34,7 @@ configuration_path="./atos-configurations"
 verbose="0"
 quiet="0"
 clean="0"
+nbruns="1"
 opt_q=""
 opt_rebuild=""
 get_results_script=""
@@ -56,6 +57,7 @@ Build Options
 Run Options
       -r <run_script> : run_script to be executed [default: $run_script]
       -t <get_results_script> : get_results_script to be executed [default: none]
+      -n <nb> : number of executions of <run_script> [default: $nbruns]
 
 Executable File Options:
       -e <executables> : executables to be instrumented [default: args of command or all generated executables]
@@ -81,7 +83,7 @@ trap "cleanup" EXIT
 tmpfile=`mktemp /tmp/atos-inst.XXXXXX`
 
 
-while getopts vhdqcfe:r:b:B:t:C: opt; do
+while getopts vhdqcfe:r:b:B:t:C:n: opt; do
     case $opt in
 	e) executables="$OPTARG"
 	    ;;
@@ -94,6 +96,8 @@ while getopts vhdqcfe:r:b:B:t:C: opt; do
 	B) remote_profile_path="$OPTARG"
 	    ;;
 	t) get_results_script="$OPTARG"
+	    ;;
+	n) nbruns="$OPTARG"
 	    ;;
 	c) clean=1
 	    ;;
@@ -170,12 +174,12 @@ else
     fi
 fi
 	
-$dir/atos-run -C "$configuration_path" $opt_q -r # Will stop there if reference run fails
+$dir/atos-run -C "$configuration_path" -n "$nbruns" $opt_q -r # Will stop there if reference run fails
 
 for gopt in "-O1" "-O2" "-Os" "-O3"; do
     for opts in "" "-flto"; do
 	options="$gopt $opts"
-	$dir/atos-opt -C "$configuration_path" $opt_q -a "$options" && $dir/atos-run -C "$configuration_path" $opt_q -r -a "$options" || true
+	$dir/atos-opt -C "$configuration_path" $opt_q -a "$options" && $dir/atos-run -C "$configuration_path" -n "$nbruns" $opt_q -r -a "$options" || true
     done
     failure=false
     $dir/atos-profile -C "$configuration_path" $opt_q -b "$remote_profile_path" -g "$gopt" || failure=true
@@ -185,7 +189,7 @@ for gopt in "-O1" "-O2" "-Os" "-O3"; do
     else
 	for opts in "" "-flto" "-funroll-loops" "-flto -funroll-loops"; do
 	    options="$gopt $opts"
-	    $dir/atos-opt -C "$configuration_path" $opt_q -u "$gopt" -a "$options" && $dir/atos-run -C "$configuration_path" $opt_q -b "$remote_profile_path" -r -u "$gopt" -a "$options" || true
+	    $dir/atos-opt -C "$configuration_path" $opt_q -u "$gopt" -a "$options" && $dir/atos-run -C "$configuration_path" -n "$nbruns" $opt_q -b "$remote_profile_path" -r -u "$gopt" -a "$options" || true
 	done
     fi
 done
